# -*- coding: utf-8 -*-
"""TesseractOCR.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Dzc6bS57Q1EEtSmrgwOTZEruOEWM1nXe
"""

# !sudo apt install tesseract-ocr
# !sudo apt install tesseract-ocr-script-hang tesseract-ocr-script-hang-vert
# !pip install pytesseract

import pytesseract
import cv2
import os
from PIL import Image

class_names = ['건강보험료납부확인서', '근로소득원천징수', '자동차등록증',
               '자동차등록원부', '자격득실확인서', '자동차매매계약서', '소득금액증명서']

def getData(url, imgType):
    toSend = dict()
    toSend['file_name'] = imgType
    img = cv2.imread(url)
    if imgType == '자격득실확인서':
        
        x, y = 786, 362
        w, h = 80, 30
        toRead = img[y:y+h, x:x+w]
        res = pytesseract.image_to_string(toRead, lang='kor')
        birth = f'{res[:2]}.{res[2:4]}.{res[4:6]}'
        toSend['생년월일'] = birth
        x, y = 328, 556
        w, h = 200, 30
        toRead = img[y:y+h, x:x+w]
        res = pytesseract.image_to_string(toRead, lang='kor')
        arr = res.split('\n')[0:-1]

        comp_name = arr
        toSend['회사명'] =  comp_name[0]

        x, y = 826, 556
        w, h = 250, 30
        toRead = img[y:y+h, x:x+w]
        res = pytesseract.image_to_string(toRead, lang='kor')
        startDate = res.split('\n')[0:-1][0]
        toSend['자격취득일'] = startDate
        print(toSend)

    elif imgType == '건강보험료납부확인서':

        x, y = 948, 290
        w, h = 170, 30
        toRead = img[y:y+h, x:x+w]
        res = pytesseract.image_to_string(toRead, lang='kor')
        toSend['생년월일'] = res.split('\n')[0:-1][0]

        x, y = 400, 340
        w, h = 180, 30
        toRead = img[y:y+h, x:x+w]
        res = pytesseract.image_to_string(toRead, lang='kor')
        arr = res.split('\n')[0:-1]
        toSend['회사명'] =  arr
        

        
        x, y = 270, 539
        w, h = 170, 30
        toRead = img[y:y+h, x:x+w]
        res = pytesseract.image_to_string(toRead, lang='kor')
        toSend['연봉'] = str(int(int(res.split()[0])*291.54))
        print(toSend)

    elif imgType == '소득금액증명서':
        x, y = 170, 1252
        w, h = 250, 30
        toRead = img[y:y+h, x:x+w]
        res = pytesseract.image_to_string(toRead, lang='kor')
        print(res)
        phone = res
        x, y = 680, 665
        w, h = 200, 30
        toRead = img[y:y+h, x:x+w]
        res = pytesseract.image_to_string(toRead, lang='kor')
        print(int(res)*12)

        toSend.append(phone)
        toSend.append(str(int(res)*12))
    
    elif imgType == '자동차매매계약서':
        x, y = 1060, 455
        w, h = 70, 30
        toRead = img[y:y+h, x:x+w]
        res = pytesseract.image_to_string(toRead, lang='kor')
        print(res)
        birth = f'{res[:2]}.{res[2:4]}.{res[4:6]}'
        x, y = 387, 505
        w, h = 200, 30
        toRead = img[y:y+h, x:x+w]
        res = pytesseract.image_to_string(toRead, lang='kor')
        phone = res
        print(phone)
        x, y = 1041, 621
        w, h = 90, 30
        toRead = img[y:y+h, x:x+w]
        res = pytesseract.image_to_string(toRead, lang='eng+kor')
        carType = res
        print(carType)
        x, y = 395, 721
        w, h = 130, 30
        toRead = img[y:y+h, x:x+w]
        res = pytesseract.image_to_string(toRead, lang='kor')
        carPrice = res
        print(carPrice)
    
    return(toSend) 

if __name__ == '__main__':
    # getData('.//data//자격득실확인서1.png', '자격득실확인서')
    getData('.//data//건강보험료납부확인서1.png', '건강보험료납부확인서')
    # getData('.//data//소득금액증명서1.png', '소득금액증명서')
    # getData('.//data//자동차매매계약서1.png', '자동차매매계약서')